### ISSUE TITLE
FontIconTextView crashes app with gradle 3.1.3

### ISSUE THREAD

**Issue by sashwini** [shamanland/fonticon#26]
We have been using this library in the app since gradle 2.3.3 but in last update to gradle 3.1.3,  FontIconTextView is broken. The project compiles fine without any warnings but when trying to load the screen, get an exception as 
android.view.InflateException: Binary XML file line #161: Error inflating class com.shamanland.fonticon.FontIconTextView
        at android.view.LayoutInflater.createView(LayoutInflater.java:637)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:920)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.ogd.biz.views.fragments.AllItemsFragmentNew.onCreateItem(AllItemsFragmentNew.java:386)
        at com.ogd.biz.views.adapters.SectionWiseItemAdapter$1.onClick(SectionWiseItemAdapter.java:189)
        at android.view.View.performClick(View.java:5047)
        at android.view.View$PerformClick.run(View.java:20286)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5491)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:611)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:920) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at com.ogd.biz.views.fragments.AllItemsFragmentNew.onCreateItem(AllItemsFragmentNew.java:386) 
        at com.ogd.biz.views.adapters.SectionWiseItemAdapter$1.onClick(SectionWiseItemAdapter.java:189) 
        at android.view.View.performClick(View.java:5047) 
        at android.view.View$PerformClick.run(View.java:20286) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5491) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
     Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x3
        at android.content.res.TypedArray.getDimension(TypedArray.java:497)
        at com.shamanland.fonticon.FontIconDrawable.inflate(FontIconDrawable.java:111)
        at com.shamanland.fonticon.FontIconDrawable.inflate(FontIconDrawable.java:65)
        at com.shamanland.fonticon.CompoundDrawables.inflateDrawables(CompoundDrawables.java:61)
        at com.shamanland.fonticon.CompoundDrawables.initCompoundDrawables(CompoundDrawables.java:81)
        at com.shamanland.fonticon.CompoundDrawables.init(CompoundDrawables.java:44)
        at com.shamanland.fonticon.FontIconTextView.<init>(FontIconTextView.java:18)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:920) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at com.ogd.biz.views.fragments.AllItemsFragmentNew.onCreateItem(AllItemsFragmentNew.java:386) 
        at com.ogd.biz.views.adapters.SectionWiseItemAdapter$1.onClick(SectionWiseItemAdapter.java:189) 
        at android.view.View.performClick(View.java:5047) 
        at android.view.View$PerformClick.run(View.java:20286) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5491) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 

I believe the line causing the issue is:
mTextSize = a.getDimension(R.styleable.FontIconDrawable_textSize, 9f);

Can anyone suggest a quick fix for this?

**Comment by christophermark** [comment]
I was running into the same issue.
Seems to be an issue with the xml file that I used to define an icon. Android Studio picked up on the issue immediately:

Old, broken:
```xml
<?xml version="1.0" encoding="utf-8"?>
<font-icon
    xmlns:android="http://schemas.android.com/apk/res-auto"
```

New, fixed:
```xml
<?xml version="1.0" encoding="utf-8"?>
<font-icon
    xmlns:android="http://schemas.android.com/apk/res/android"
```

**Comment by christophermark** [comment]
Update, we just transitioned onto https://github.com/kazy1991/FontDrawable instead.
